Methods branch
RoodzFernando/Enumerable-Methods pull request #1
Opened 2019-11-25 17:09 UTC by RoodzFernando

The enumerable module sent for code review. Thank You!

2019-11-25 18:10 UTC, ebukaume requested changes
Hi @RoodzFernando :wave: 

Nice job so far. However, most of your methods are not behaving the way they should. You may need to look at the docs to have a solid grasp of the expected behaviours of ruby enumerable methods.

_See below for more_

**Kindly submit another code review after fixing the issues.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-11-25 18:10 UTC, ebukaume commented on enumerables.rb
> +  # my_all?
These comments are not necessary. Your method definitions are just enough here.

2019-11-25 18:10 UTC, ebukaume commented on enumerables.rb
> +  end
In ruby, all methods that end in `?` return Boolean. Try this in your environment:

`[1, :s, 'a', {}].all?`

Is your own implementation working like ruby all? method? :wink: 

Also, `all?` optionally accepts an argument but your implementation does not. Also, account for different kinds of input types. Refer to [the docs](https://devdocs.io/ruby~2.6/enumerable)

2019-11-25 18:10 UTC, ebukaume commented on enumerables.rb
> +
Same as above

2019-11-25 18:10 UTC, ebukaume commented on enumerables.rb
> +  end
Same as above

2019-11-25 18:10 UTC, ebukaume commented on enumerables.rb
> +  end
What happens when block is not given? `[1, 2, :s, 'a'].count` 

Or when the user passes an argument? [1, 2, :s, 'a'].count(1)`. 

Did you consider when proc is passed? [1, 2, :s, 'a'].count(&some_procedure)`

2019-11-25 18:10 UTC, ebukaume commented on enumerables.rb
> +  # end
Remove this commented code. If you need to review a previous version of your code, use git history.

2019-11-25 18:10 UTC, ebukaume commented on enumerables.rb
> +      puts 'No block given'
No debugging information should be pushed to the repo. Please remove it. You can raise an error if need be.

2019-11-25 18:10 UTC, ebukaume commented on enumerables.rb
> +end
What happens when a proc is passed? What of when neither a block nor an argument is passed? Compare it with the ruby `#map` method.

2019-11-25 18:10 UTC, ebukaume commented on enumerables.rb
> +      end
Did you test for when it is called on a range? Remember, the Range class also includes the Enumerable method.

Also, what should happen when a block is not given? 

`[1,2,3,4,5].my_inject(:+)` should equal `15` not `nil`

2019-11-26 17:44 UTC, RoodzFernando commented
I have all the bugs fixed!

2019-11-26 18:41 UTC, stratospherique requested changes
### Great Progress @RoodzFernando :clap: However, after the last commited changes, some errors have emerged for some edgy test cases. check :arrow_down: 

- **[REQUIRED]** check the code comments below, use the notes and examples to refactor your code :gear: 

### That's it :relieved: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2019-11-26 18:41 UTC, stratospherique commented on enumerables.rb
> +  end
* [ ] my_any? should be able to receive classes, literals, regex exp, etc as **arguments** :no_entry_sign: 

* [ ] my_any? returns true if the block ever returns a value other than false or nil
  ```ruby
    array = [1,2,5,4,7]
    true_block = proc {|num| num < 10 }
    p array.my_any?(&true_block) == array.any?(&true_block) # false
  ```

2019-11-26 18:41 UTC, stratospherique commented on enumerables.rb
> +  end
* [ ] my_none? should be able to receive classes, literals, regex exp, etc as **arguments** :no_entry_sign: 

* [ ] my_none? returns true if the block never returns true for all elements
  ```ruby
    array = [1,2,5,4,7]
    true_block = proc {|num| num > 10 }
    p array.my_none?(&true_block) == array.none?(&true_block) # false
  ```

2019-11-26 18:41 UTC, stratospherique commented on enumerables.rb
> +  end
* [ ] my_count returns the number of items in enum through enumeration
  ```ruby
    array = [1,2,5,4,7]
    p array.my_count == array.count # returns this error
      #
      # NameError:
      #  undefined local variable or method `arg' for #<Array:0x000055b627046ab8>
      #  Did you mean?  _args
      # ./enumerables.rb:91:in `my_count'
  ```    

* [ ] my_count counts the number of items in enum that are equal to item if an argument is given 
     ```ruby
    array = [1,2,5,4,7,1,8,7,1]
    p array.my_count(1) == array.count(1) # returns this error
      #
      # NameError:
      #  undefined local variable or method `arg' for #<Array:0x000055b627046ab8>
      #  Did you mean?  _args
      # ./enumerables.rb:91:in `my_count'
  ```

2019-11-26 18:41 UTC, stratospherique commented on enumerables.rb
> +  end
* [ ] my_map returns an Enumerator if no block is given
   ```ruby
    array = [1,5,8,7,9,5,5,55,5]
    p array.my_map #error
    LocalJumpError:
        no block given (yield)
      # ./Enumerable_Methods.rb:89:in `block in my_map'
      # ./Enumerable_Methods.rb:12:in `my_each'
      # ./Enumerable_Methods.rb:88:in `my_map'
  ```

* [ ] my_map returns a new array with the results of running block once for every element in enum.
  ```ruby
    array = [1,2,5,4,7]
    block = proc { |num| num < (1 + 9) / 2 }
    p array.my_map?(&block) == array.map?(&block) # false
  ```

2019-11-26 18:41 UTC, stratospherique commented on enumerables.rb
> +  end
* [ ] my_inject combines all elements of enum by applying a binary operation, specified by a block
  ```ruby
    range = Range.new(5, 50)
    p range.my_inject(4) { |prod, n| prod * n } # returns this error
    #NoMethodError:
    #    undefined method `[]' for 5..50:Range
      # ./enumerables.rb:11:in `block in my_each'
      # ./enumerables.rb:10:in `each'
      # ./enumerables.rb:10:in `my_each'
      # ./enumerables.rb:108:in `my_inject'
  ```

* [ ] my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method
  ```ruby
    range = Range.new(5, 50)
    p range.my_inject(2, :*) # returns this error
    #NoMethodError:
    #    undefined method `[]' for 5..50:Range
      # ./enumerables.rb:11:in `block in my_each'
      # ./enumerables.rb:10:in `each'
      # ./enumerables.rb:10:in `my_each'
      # ./enumerables.rb:115:in `my_inject_sym'
      # ./enumerables.rb:102:in `my_inject'
  ```

2019-11-27 01:00 UTC, Forison requested changes
# Hi @RoodzFernando,
Good job on implementing the changes some of the changes suggested in the previous review.
Here are a few flaws you have to address to have the project approved💪.
See below⬇️
## That is it, Kindly do these changes and submit the project for review
#### Happy coding😇
#### @Forison

2019-11-27 01:00 UTC, Forison commented on enumerables.rb
> +end
` array = [1,2,5,4,7] `
  `block = proc { |num| num < (1 + 9) / 2 }`
  `p array.my_map?(&block) =  array.map?(&block)` # false`

2019-11-27 01:00 UTC, Forison commented on enumerables.rb
> +  end
`range = Range.new(5, 50)`
  ` p range.to_a.my_inject(4) { |prod, n| prod * n }`   #still returns this error
   compare to the real ```inject```
  `p range.inject(4) { |prod, n| prod * n }`

2019-11-27 01:00 UTC, Forison commented on enumerables.rb
> +  end
` range = Range.new(5, 50) `
 ` p range.my_inject(2, :*) ` # returns this error
compare it to the result you get using the real ```inject```
 ` p range.inject(2, :*) `

2019-11-27 16:30 UTC, RoodzFernando commented
p array.my_map?(&block) = array.map?(&block) # false` (This enumerable works for me maybe it is because the original map does not take the question at his end.) (https://devdocs.io/ruby~2.6/enumerable#method-i-map) check the documentation please fro more information. Thank you!

2019-11-27 17:39 UTC, whiz25 requested changes
## Good job :+1: 
Nice work implementing the suggested changes. I tested your methods and they cover some edge cases which is good. However, we can't merge this one yet. So check my comments for changes to be made and resend for another review.

### Martin Afani

2019-11-27 17:41 UTC, whiz25 commented on enumerables.rb
> +  end
- [ ] when a class is passed as an argument returns true if all of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-11-27 17:42 UTC, whiz25 commented on enumerables.rb
> +  end
- [ ] returns true if the block ever returns a value other than false or nil
- [ ] when no block or argument is given returns true if at least one of the collection is not false or nil
- [ ] when a class is passed as an argument returns true if at least one of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2019-11-27 17:43 UTC, whiz25 commented on enumerables.rb
> +  end
- [ ] returns true if the block never returns true for all elements
- [ ] when no block or argument is given returns true only if none of the collection members is true
- [ ] when a class is passed as an argument returns true if none of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns true only if none of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-11-27 17:44 UTC, whiz25 commented on enumerables.rb
> +  end
- [ ] combines all elements of enum by applying a binary operation, specified by a block
- [ ] when a symbol is specified combines each element of the collection by applying the symbol as a named method

2019-11-27 19:53 UTC, imhta requested changes
# Changes Required 🛑 

### Hello @RoodzFernando, 👋  Still you didn't fix the previous code review comments. and your project is failing in the same tests like before. So kindly fix and then make another code review request.

**Happy coding,**
 Pon Muthu Selvam N
_If you have any queries feel free ping me in slack_

2019-11-27 20:25 UTC, whiz25 approved these changes
## Hey @RoodzFernando 
You haven't made any changes as far the previous reviews are concerned. The same edge cases are still failing. But I am giving you the :+1: because this has been a long review for you and therefore the max number of review cycle has been reached.
#### Please try to make the suggested changes for your learning.

### Martin Afani

2019-11-27 22:06 UTC, merged